wsdl: "https://speller.yandex.net/services/spellservice?WSDL"
url: "https://test-stand.gb.ru/gateway/login"
posts: "https://test-stand.gb.ru/api/posts"
users: "https://test-stand.gb.ru/api/users"
username: 'ivanivanov697'
password: 'bb5e16295e'
title: 'New post for test 3'
description: 'Description of the new test post'
content: 'You can add any content here'